---

name: NodeJS CI test

on:
  push:
    branches: ["main", "test*"]
    tags: ["v1.*.*"]
  pull_request:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Use nodejs
      uses: actions/setup-node@v3
      with: 
        node-version: 18
        cache: 'npm'

    - name: install NPM packages
      run: npm install

    - name: run test
      run: npm test
      
    - name: Docker build
      run: |
        docker build --tag ${{ github.repository }}:${GITHUB_SHA::6} .
        docker tag ${{ github.repository }}:latest
